### ISSUE TITLE
align dedup condition seems wrong.

### ISSUE THREAD

**Issue by logust79** [edg1983/WGS_pipeline#1]
Very nice pipeline!
I noticed this line here:
https://github.com/edg1983/WGS_pipeline/blob/main/modules/align_dedup/align_dedup.nf#L9
Is it a bug?

**Comment by edg1983** [comment]
Yep! Nice catch! 
Definitely this should be GRCh38... 

I've just pushed a commit a to fix this.

**Comment by logust79** [comment]
Awesome :)
